import { BOARD_COL_COUNT } from '#/sim/helpers/constants'

export const SIDEBAR_UNITS = 26
const BOARD_UNITS_RAW = 100 - SIDEBAR_UNITS
const HEX_BORDER_PROPORTION = 0.5
const HEX_BORDER_SIZES_PROPORTION = (BOARD_COL_COUNT + 1) * HEX_BORDER_PROPORTION
export const HEX_SIZE_UNITS = (BOARD_UNITS_RAW - HEX_BORDER_SIZES_PROPORTION) / BOARD_COL_COUNT
