import { BOARD_COL_COUNT } from '#/sim/helpers/constants'

const SIDEBAR_UNITS_RAW = 26
const BOARD_UNITS_RAW = 100 - SIDEBAR_UNITS_RAW
const HEX_BORDER_PROPORTION = 0.5
const HEX_BORDER_SIZES_PROPORTION = (BOARD_COL_COUNT + 1) * HEX_BORDER_PROPORTION
const HEX_SIZE_PROPORTION = (BOARD_UNITS_RAW - HEX_BORDER_SIZES_PROPORTION) / BOARD_COL_COUNT

export const SIDEBAR_UNITS = `${SIDEBAR_UNITS_RAW}vw`
export const HEX_BORDER_UNITS = `${HEX_BORDER_PROPORTION}vw`
export const HEX_UNITS = `${HEX_SIZE_PROPORTION}vw`
export const HALF_HEX_BORDER_UNITS = `${HEX_BORDER_PROPORTION / 2}vw`
export const HALF_HEX_UNITS = `${HEX_SIZE_PROPORTION / 2}vw`
export const QUARTER_HEX_INSET_UNITS = `-${HEX_SIZE_PROPORTION / 4}vw`
export const HEX_GAP_BETWEEN_SIDE_EDGES_UNITS = `${HEX_SIZE_PROPORTION / 4 + HEX_BORDER_PROPORTION}vw`
